### PR TITLE
941 - Fix angular property binding

### LINKED ISSUE #941: Angular: Property binding issues
**Describe the bug**
Noticing issues in components in angular where attributes need property binding in order to work properly.

- ids-toggle-button https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-toggle-button/demos/example/example.component.html#L9
- ids-search-field (in ids-app-menu) https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-app-menu/demos/example/example.component.html#L59
- ids-menu-button https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-menu-button/demos/example/example.component.html#L15
- ids-pager https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-pager/demos/example/example.component.html#L10
- ids-text (color attribute)

**To Reproduce**

1. Clone https://github.com/infor-design/enterprise-wc-examples 
2. `cd angular-ids-wc`
3. `npm i && start`
4. Remove property bindings in above lines and see the errors on the following examples:
5. http://localhost:4200/ids-toggle-button/example
6. http://localhost:4200/ids-app-menu/example
7. http://localhost:4200/ids-menu-button/example
8. http://localhost:4200/ids-pager/example

**Expected behavior**
Be able to add settings without property binding

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
#931

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed to angular where attributes property binding was not work properly for:
- ids-toggle-button
- ids-app-menu
- ids-menu-button
- ids-pager
- ids-text
- ids-toolbar
- Added new `ids-text` example in angular examples repo

**Related github/jira issue (required)**:
Closes #941
Related to #931

**Steps necessary to review your pull request (required)**:
- Pull WC branch ([941-angular-property-binding](https://github.com/infor-design/enterprise-wc/tree/941-angular-property-binding)) and build/run
- Use `npm run publish:link` to push WC branch to local NPM repo for linking
- Pull the latest copy of main from the WC Examples repo
- Pull WC Examples branch ([941-angular-property-binding](https://github.com/infor-design/enterprise-wc-examples/tree/941-angular-property-binding)), or use `main` WC Examples branch after PR ([NG#28](https://github.com/infor-design/enterprise-wc-examples/pull/28)) merged
- Switch to `angular-ids-wc` examples directory, and run `npm i && npm link ids-enterprise-wc`
- Use `npm run start` to run the angular examples demo app
- Navigate to below examples and see all attributes should working properly
- http://localhost:4200/ids-toggle-button/example
- http://localhost:4200/ids-toggle-button/icon-align-right
- http://localhost:4200/ids-app-menu/example
- http://localhost:4200/ids-app-menu/example-footer
- http://localhost:4200/ids-menu-button/example
- http://localhost:4200/ids-menu-button/disabled
- http://localhost:4200/ids-menu-button/display-selected
- http://localhost:4200/ids-pager/example
- http://localhost:4200/ids-pager/list
- http://localhost:4200/ids-pager/sandbox
- http://localhost:4200/ids-text/example

Also smoke test WC demo app
- http://localhost:4300/ids-toggle-button
- http://localhost:4300/ids-app-menu
- http://localhost:4300/ids-menu-button
- http://localhost:4300/ids-pager
- http://localhost:4300/ids-data-grid/pagination-client-side.html
- http://localhost:4300/ids-data-grid/pagination-server-side.html
- http://localhost:4300/ids-data-grid/pagination-standalone.html
- http://localhost:4300/ids-text/typography.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jmacaluso711 — DISMISSED** [review]
Looks good to me. Also tested in the NG repo with npm link 👍

File: src/components/ids-pager/ids-pager-dropdown.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { customElement, scss } from '../../core/ids-decorators';
 import { attributes } from '../../core/ids-attributes';
-// import { stringToBool } from '../../utils/ids-string-utils/ids-string-utils';
```
Comment (tmcconechy) [inline src/components/ids-pager/ids-pager-dropdown.ts:3]: Could remove?

**Review by tmcconechy — COMMENTED** [review]
Looks good - really minor thing. But also wondering the reason why some need overridden attributeChangeCallback?

File: src/components/ids-pager/ids-pager-dropdown.ts (hunk 1 above)
Comment (deep7102) [reply src/components/ids-pager/ids-pager-dropdown.ts:3]: 1. Yes, it removed `stringToBool` import because it was not used anywhere in this file.
2. The reason it need overridden `attributeChangeCallback` because the way pager setup to keep in sync attributes/props with its parent/children.

File: doc/CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,7 @@
 
 - `[DataGrid]` Added row-recycling pattern and caching to improve virtual-scroll performance. ([#972](https://github.com/infor-design/enterprise-wc/issues/972))
 - `[DataGrid]` Fixed arrow-keys on virtual-scroll and added scrollRowIntoView() method. ([#929](https://github.com/infor-design/enterprise-wc/issues/929))
+- `[General]` Fixed to angular examples where attributes property binding was not work properly for ids-toggle-button, ids-app-menu, ids-menu-button, ids-pager, ids-text, ids-toolbar. ([#941](https://github.com/infor-design/enterprise-wc/issues/941))
```
Comment (tmcconechy) [inline doc/CHANGELOG.md:12]: BTW @deep7102 can you put this in the new Beta 4 section now?

**Review by tmcconechy — COMMENTED** [review]
ok looks good - just one thing

File: doc/CHANGELOG.md (hunk 2 above)
Comment (deep7102) [reply doc/CHANGELOG.md]: Updated now, the change log

**Review by clayinfor — APPROVED** [review]
👍

File: src/components/ids-pager/ids-pager-button.ts [hunk 3]
```diff
@@ -63,25 +68,68 @@ export default class IdsPagerButton extends Base {
     ];
   }
 
+  /**
+   * React to attributes changing on the web-component
+   * @param {string} name The property name
+   * @param {string} oldValue The property old value
+   * @param {string} newValue The property new value
+   */
+  attributeChangedCallback(name: string, oldValue: string, newValue: string) {
```
Comment (clayinfor) [inline src/components/ids-pager/ids-pager-button.ts:77]: Please remind again, what's the use-case for attributes being changed directly on the button?

Comment (deep7102) [reply src/components/ids-pager/ids-pager-button.ts:77]: @clayinfor 
It is not directly changing, but it gets changed thru it's parent `ids-pager` by `#syncChildren(name, newValue)` mrthod

Comment (clayinfor) [reply src/components/ids-pager/ids-pager-button.ts:77]: In that case, I'm not sure we'll need the `attributeChangedCallback` here ... it's only useful if there's a use case where `ids-pager-button` attributes need to be changed directly... also, if the button is ever used in a standalone fashion, we could justify having `attributeChangedCallback`... 

On the AngularJS side, the parent `<ids-pager>` element will be loaded first, and then it will load children like `<ids-pager-button>` which will subsequently trigger`IdsPagerButton.connectedCallback`, and the code to set attributes on `<ids-pager-button>` will fire within this `connectedCallback`... so, I'm assuming the `attributeChangedCallback` should not be needed for the sake of AngularJS either... but let me know if this is wrong assumption.

Comment (deep7102) [reply src/components/ids-pager/ids-pager-button.ts:77]: Sure, let me try 👍 
if it works I like more that way because of less and more clean stuff

Comment (tmcconechy) [reply src/components/ids-pager/ids-pager-button.ts:77]: I'll put this to WIP for now?

Comment (clayinfor) [reply src/components/ids-pager/ids-pager-button.ts:77]: It turns out that we do need the `IdsPagerButton.attributeChangedCallback()` method because `IdsPager.#syncChildren()` makes a call directly to `element.setAttribute()` which in turn will trigger all attributeChangedCallbacks on the child-components.

Comment (tmcconechy) [reply src/components/ids-pager/ids-pager-button.ts:77]: So this is good to merge for now?

Comment (deep7102) [reply src/components/ids-pager/ids-pager-button.ts:77]: Yes, it all ready to merge now
