### PR TITLE
1169 - Added borderless setting for card/widget

### LINKED ISSUE #1169: Widget/Card: Add setting to remove the borders
**Describe the bug**
Add a setting to cards so that the border and box shadow will be hidden. Needs some answers on https://jira.infor.com/browse/ICE-85 before starting

**Expected behavior**
New class "border-less" that hides it

**Additional context**
https://jira.infor.com/browse/ICE-85

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the details for making this change. What existing problem does the pull request solve?**

Added border-less attribute for card/widget

**Related github/jira issue (required)**:

Closes #1169 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4300/ids-card/borderless.html
- Should have no borders
- Check other modes

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

File: src/components/ids-card/ids-card.ts [hunk 1]
```diff
@@ -287,6 +287,23 @@ export default class IdsCard extends Base {
...
 
+  /**
+   * Set the card to borderless
+   * @param {boolean|null} value If card should be borderless or not
+   */
+  set borderless(value) {
+    const val = stringToBool(value);
+    if (stringToBool(value)) {
+      this.setAttribute('border-less', String(val));
+      if (this.container) this.redraw();
```
Comment (andriivarhanov) [inline src/components/ids-card/ids-card.ts:298]: it looks like we don't need to `this.redraw()` the card since the attribute used for CSS and doesn't change any content or size

File: src/components/ids-card/ids-card.ts [hunk 2]
```diff
@@ -287,6 +287,23 @@ export default class IdsCard extends Base {
...
+      return;
+    }
+    this.removeAttribute('border-less');
+    if (this.container) this.redraw();
+  }
+
+  get borderless() { return this.getAttribute('border-less'); }
```
Comment (andriivarhanov) [inline src/components/ids-card/ids-card.ts:305]: `stringToBool` needed here as well

**Review by andriivarhanov — COMMENTED** [review]
looks good, just a couple of small adjustments

**Comment by deep7102** [comment]
1. Add `border-less` attribute to the `src/core/ids-attributes.ts` file - as @andriivarhanov 
2. Add `border-less` attribute to observable attributes array `static get attributes() {}`
```
static get attributes() {
    return [
      ...super.attributes,
      attributes.BORDER_LESS,
      ...
    ];
  }
```
3. Getter/setter also can be more simple, no need to call multiple times `stringToBool()` and no need to redraw.
```
  set borderLess(value: boolean | null) {
    if (stringToBool(value)) this.setAttribute(attributes.BORDER_LESS, '');
    else this.removeAttribute(attributes.BORDER_LESS);
  }

  get borderLess(): boolean {
    return this.hasAttribute(attributes.BORDER_LESS);
  }
```

**Review by tmcconechy — DISMISSED** [review]

**Review by deep7102 — DISMISSED** [review]
Looks good!
thanks @yohannahbautista

**Review by andriivarhanov — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]
