### PR TITLE
2249 - Add fixes for typahead

### LINKED ISSUE #2249: IdsDropdown: Search (typeahead) is not working as expected in Angular Web Components.
**Describe the bug**
While using typeahead on Ids Dropdown it is not working as expected. It cannot search the fields in the dropdown list. 

**To Reproduce**

https://stackblitz.com/edit/ids-enterprise-wc-100-nkbpsr?file=index.html

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-100-nkbpsr?file=index.html.
2. Click on the above Stack blitz link and try to search a field from the list
3. See error that it will not search any of the field as typeahead is not working as expected.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes an issue that due to build order some of the settings need to be set at a different time. Also updated a few dependencies (didnt fix the issue but brings things up to date)

**Related github/jira issue (required)**:
Fixes #2249 

**Steps necessary to review your pull request (required)**:
- pull this branch
- http://localhost:4300/ids-dropdown/typeahead.html should work for typehead (type c in the field)
- now run `npm run build:dist`
- pull latest https://github.com/infor-design/enterprise-wc-examples
- copy build/dist/development contents to enterprise-wc-examples/plain-html/node_modules/ids-enterprise-wc
- go to `plain-html` in the console and run `npm run start`
- test the typahead both works in this page and the position of the dropdown looks ok

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-popup/ids-popup.ts [hunk 1]
```diff
@@ -890,6 +890,7 @@ export default class IdsPopup extends Base {
    * @param {string} val the position style string
    */
   set positionStyle(val: string) {
+    console.log(val, POSITION_STYLES);
```
Comment (andrivarhanov) [inline src/components/ids-popup/ids-popup.ts:893]: please remove console.log

**Review by andrivarhanov — APPROVED** [review]

**Review by clayinfor — APPROVED** [review]
