### PR TITLE
143 - Add ids splitter

### LINKED ISSUE #143: IdsSplitter: Add new web component
**Describe the bug**

Bring over the current splitter component.  See if we can simplify and improve the code at all while improving as we go. Current splitter component https://master-enterprise.demo.design.infor.com/components/splitter

```
Markup to be added
```

**Functionality to bring over**
- Supports both x and y splitter
- Supports nesting in both cases important https://github.com/infor-design/enterprise/issues/2697
- May need a parent container in the pattern
- Keep current designs
- Resizes inner containers to 100% those items are slots

**Additional context**
- 100% test coverage
- DOCS, CHANGE log ect. 
- https://github.com/infor-design/enterprise-wc/blob/master/doc/CHECKLIST.MD
- themes 

See completed components like card, tag, badge, hyperlink as reference

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
- Added Ids Splitter component
- Updated ids-draggable to have translateX/Y with events detail

**Related github/jira issue (required)**:
Closes #143

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300
- http://localhost:4300/ids-splitter
- http://localhost:4300/ids-splitter/sandbox.html
- http://localhost:4300/ids-splitter/side-by-side.html
- See splitter all variations and uplift styles 
- Added e2e and functional tests
- See the docs

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-splitter/ids-splitter.js [hunk 1]
```diff
@@ -0,0 +1,1219 @@
...
+  /**
+   * Return the attributes we handle as getters/setters
+   * @returns {Array} The attributes in an array
+   */
+  static get attributes() {
+    return [
+      ...super.attributes,
+      attributes.ALIGN,
+      attributes.AXIS,
+      attributes.LABEL,
```
Comment (tmcconechy) [inline src/components/ids-splitter/ids-splitter.js:78]: Alphabetize

File: src/components/ids-splitter/README.MD [hunk 2]
```diff
@@ -0,0 +1,220 @@
+# Ids Splitter Component
+
+The Ids Splitter is used to divides the user interface of a screen. It is composed of resizable "panes" which divide content laid out either horizontally or vertically
```
Comment (tmcconechy) [inline src/components/ids-splitter/README.MD:3]:
```suggestion
The Ids Splitter is used to divide the user interface of a page. It is composed of resizable "panes" which divide content. It can layout either horizontally or vertically along an axis where a user can resize the panes, these are represented as `<ids-splitter-pane>` components.
```

File: src/components/ids-splitter/README.MD [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+along an axis where a user can resize the panes, these are represented as `<ids-splitter-pane>` components.
```
Comment (tmcconechy) [inline src/components/ids-splitter/README.MD:4]:
```suggestion
```

File: src/components/ids-splitter/README.MD [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+
+![Different variations of IdsSplitterLayout](./doc/ids-splitter-markup-legend.png)
+
+The pane can move to the left or the right of the screen. This allows the user to have control of the customized layout. Elements inside and outside the pane will be resized to fit.
```
Comment (tmcconechy) [inline src/components/ids-splitter/README.MD:8]:
```suggestion
The pane can move to the left or the right of the screen. This allows the user to have control of the customized layout. Elements inside and outside the pane will be resized to fit depending on if their css is fluid.
```

**Review by tmcconechy — COMMENTED** [review]
I think this looks fantastic. Only a few minor suggestions.

1. Can remove package-lock.json my guess is your on node 14 so can do `nvm use` for this project
2. in terms of functionality the only think i saw was if you tab the splitters when you get to the last one it seems to be in the wrong tab order.

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — COMMENTED** [review]
Looks great @deep7102, very very thorough.  I found one issue we probably want to address before merging:

I accidentally right-clicked the splitter handle and it had this weird behavior where the drag was still occuring after I dismissed the right-click menu, and it took a second click to end the drag.  On the vertical splitters, this had a weird effect that causes the sizing to appear off:

Untitled_-Nov-8-2021-9_15-AM

I think this could probably be fixed one of two (or both?) ways:
- The `mousedown` event should occur only when `e.button === 0` (left click only)
- Could also attach a `contextmenu` event handler to splitter handles that returns false (maybe not necessary if we do the first part)

File: src/components/ids-splitter/ids-splitter.js (hunk 1 above)
Comment (deep7102) [reply src/components/ids-splitter/ids-splitter.js]: Updated now

**Comment by deep7102** [comment]
Thanks! @EdwardCoyle the right click stuff was good catch, its updated and fixed now.

**Review by tmcconechy — APPROVED** [review]

**Review by jmacaluso711 — COMMENTED** [review]
Looks fantastic @deep7102 .. Just seeing one thing in the vertical example. Seems like when you set `align="end"` there is an extra splitter being appended that is draggable outside the current splitter:

Screen Shot 2021-11-11 at 3 08 19 PM

**Comment by deep7102** [comment]
Thanks! @jmacaluso711 updated now.

**Review by jmacaluso711 — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
