### PR TITLE
922 - IdsEditor fix toolbar font/text is not readable in Safari browser

### LINKED ISSUE #922: IdsEditor: Toolbar font/text is not readable in safari browser
**Describe the bug**
Toolbar font/text is not readable in safari browser

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-editor/example.html
2. Notice that the fonts/texts in editor toolbar is not easily readable
3. Verify each mode
4. The issue is more noticeable in dark mode
5. toolbar font/text is not readable in safari browser

**Expected behavior**
Font/text should be readable

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
https://www.screencast.com/t/9pc0tgxP

**Platform**

 - OS Version: [iOS 8]
 - Browser Name: [safari]

**Additional context**

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds adjustment for `ids-color-variant-mixin` to be able to add CSS class `color-variant-alternate-formatter` in connected callback what fixes buttons color in `ids-editor` toolbar in Safari browser and possibly the color variant functionality in other components for Safari browser

**Related github/jira issue (required)**:
Closes #922

**Steps necessary to review your pull request (required)**:
- pull and run
- go to http://localhost:4300/ids-editor/example.html in Safari browser
- see the fonts/texts in editor toolbar have correct color
- change mode to dark and contrast mode
- see the fonts/texts in editor toolbar have correct color

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-input/ids-input.ts [hunk 1]
```diff
@@ -828,7 +828,9 @@ export default class IdsInput extends Base {
    */
   set cursor(value: string) {
     this.setAttribute(attributes.CURSOR, value);
-    this.input.style.cursor = value;
+    if (this.input) {
+      this.input.style.cursor = value;
```
Comment (tmcconechy) [inline src/components/ids-input/ids-input.ts:832]: Could also do:
```
this.input.style.setProperty('cursor', value)
```
(prevents need for the if/branch)

**Review by tmcconechy — DISMISSED** [review]
Just one suggestion but is cosmetic...(I reran the tests once to see if there was a temporary issue)

File: src/components/ids-input/ids-input.ts (hunk 1 above)
Comment (andriivarhanov) [reply src/components/ids-input/ids-input.ts]: @tmcconechy it works, thanks

**Review by tmcconechy — APPROVED** [review]

**Review by jmacaluso711 — APPROVED** [review]
