### PR TITLE
1136 - Add hidden theme switcher example

### LINKED ISSUE #1136: IdsThemeSwitcher: Error When menu is not included / Cannot be hidden
**Describe the bug**
Noticed in MS Teams and reported. It is not possible to make an ids-theme-switcher hidden and use it to control themes.

**To Reproduce**

1.  Make a page with `<ids-theme-switcher mode="dark" hidden></ids-theme-switcher>`
2. Load the page
4. See errors a) an error configureMenu not found b) it is not hidden

**Expected behavior**
Can hide a theme switcher as mentioned in the docs

**Additional context**
[Add any other context about the problem here.
](https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1676217716239?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1676217716239&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1676217716239&allowXTenantAccess=false)

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Quick fix for being able to hide a theme switcher. Added a guard and css to hide it. As noted in support chat

**Related github/jira issue (required)**:
Fixes #1136 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-theme-switcher/hidden.html
- theme switcher should be hidden and theme should be set to dark
- try and change the theme to light in the <ids-theme-switcher> in the DOM

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-theme-switcher/ids-theme-switcher.ts [hunk 1]
```diff
@@ -36,6 +35,7 @@ export default class IdsThemeSwitcher extends Base {
   connectedCallback() {
     super.connectedCallback();
     this.popup = this.shadowRoot?.querySelector('ids-popup-menu');
+    this.menuButton = new IdsMenuButton();
```
Comment (clayinfor) [inline src/components/ids-theme-switcher/ids-theme-switcher.ts:38]: hey @tmcconechy , was this intentional? Setting `this.menuButton` twice, on this line, and the line immediately following?

**Review by clayinfor — APPROVED** [review]
👍

File: src/components/ids-theme-switcher/ids-theme-switcher.ts (hunk 1 above)
Comment (tmcconechy) [reply src/components/ids-theme-switcher/ids-theme-switcher.ts]: Yes it was but it is a workaround for a tree shaking issue. I decided to take it out of the issue and i'll make a new issue for the problem. I'll probably reach out and discuss it. but for now its gone

**Review by clayinfor — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
