### PR TITLE
789 - Fix lifecycle issues

### LINKED ISSUE #789: Bug: Failed to construct 'CustomElement'
**Describe the bug**
Some components are giving an error: `Failed to construct 'CustomElement'`. This happens when the constructor (read template).  Makes writes. For example writing a setter.

**Task**
1. Make a test that can identify this
2. Run it on all components
3. See which needs fixed
4. Fix it

**Additional context**
Also this react is having.  Some related issues. We may need to fix this by changing that we load the template in the connectedCallback NOT the constructor

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

We have been setting up the components in a way that did not work on things like `document.createElement('ids-component')` and caused the need for workarounds / requestAnimationFrames.

In order to fix this we changed the core and updated all components as needed. The new order is:

```
constructor() // setters called with no container
connectedCallback() // settersCalled with container/shadowRoot
mountedCallback() // Should avoid
```

Before it was

```
constructor() // settersCalled with container/shadowRoot
connectedCallback() 
rendered() // Should avoid
```

**Additionally**
- rendered renamed to mountedCallback
- some rerender renamed to redraw
- minor fixes while testing pages

**Whats Left**
- Some tests skipped need to be fixed later
- Some cases dont work on every component  https://github.com/infor-design/enterprise-wc/issues/824
- @clayinfor will need to fix pager and do an additional PR, pager is broken in block grid, datagrid, listview and https://github.com/infor-design/enterprise-wc/pull/790 should be worked in
- Any additional fixes on a future PR if found
- Possibly some tests
- @EdwardCoyle working on popup, popup menu (IdsPopupMenu,  IdsMenu tests do fail and will need to be fixed on skipped)

**Related github/jira issue (required)**:
Fixes #789 
Fixes https://github.com/infor-design/enterprise-wc/issues/599
Fixes https://github.com/infor-design/enterprise-wc/issues/824 (majority)

**Steps necessary to review your pull request (required)**:
- too much to review but all components have been manually tested and all tests should pass
- sorry for any merge conflicts on your open branches

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jdilag90** [comment]
Looks like changing locale via ids-theme-switcher is broken. 
http://localhost:4300/ids-hyperlink/example.html (or other demo example pages)
It resets value back to English after selecting another locale

File: src/components/ids-dropdown/ids-dropdown.ts [hunk 1]
```diff
@@ -148,11 +148,25 @@ export default class IdsDropdown extends Base {
           ${this.validate ? ` validate="${this.validate}"` : ''}
           ${this.validate && this.validationEvents ? ` validation-events="${this.validationEvents}"` : ''}
         >
+<<<<<<< HEAD
           <ids-text audible="true">Dropdown Button</ids-text>
           <ids-icon slot="icon" icon="dropdown" part="icon"></ids-icon>
         </ids-trigger-button>
       </ids-trigger-field>
       <ids-popup type="dropdown" part="popup">
+=======
```
Comment (jmacaluso711) [inline src/components/ids-dropdown/ids-dropdown.ts:157]: Just came across this merge conflict while working on the Angular examples

Comment (tmcconechy) [reply src/components/ids-dropdown/ids-dropdown.ts]: ok i merged on main and fixed this conflict (and others). I did not finish testing dropdown 100% yet but the page is working on a shallow test
