### PR TITLE
551: Fix IdsColorPicker and IdsColor remaining features

### LINKED ISSUE #551: IdsColorPicker: Remaining Features/Issues
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] https://main-enterprise.demo.design.infor.com/components/editor/example-index.html - editor version
- [x] Fix the keyboard (arrow down , enter, keys around the colors ect), and fix focus state around swatches
- [x] Tooltip on the colors
- [x] Fix all the states [See example](https://main-enterprise.demo.design.infor.com/components/dropdown/test-states.html) and [also see](https://main-enterprise.demo.design.infor.com/components/colorpicker/test-states.html)
- [x] Check Styles match with 4.x on the popup container - swatch/hover/spacing/selected state on swatches
- [x] Default color list should load from our theme palette `node_modules/ids-identity/dist/theme-new/tokens/web/ui.config.color-palette.js`
- [x] Check mark color should change based on swatch background (check mark color can get from colorlist -arrowClass)
- [ ] Standardize/Abstract out Popup/Picker/"return value" interface (to be used in this and other pickers)
- [x] Check JSDoc comments for everything that's missing
- [x] Add test for change event firing
- [x] Add test for setting color / clearing color
- [x] Change hide/show to open/close for consistency and make sure it fires events that are documented
- [x] Ability to set custom labels for selections. Should be able to show color-name `azure06` or `color-hex` `#ffffff` inside the input. [See example](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html)
- [x] Show label instead of hex. [See example](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-show-label.html)
- [x] Add sizes widths and field heights. [See Ids Input](https://main.wc.design.infor.com/ids-input/)
- [x] Add dirty tracker example to [the example page](https://main.wc.design.infor.com/ids-color-picker/)

**Minor**

- [ ] Some text hard coded in component, should give setting/slots to user change those text strings ids-text audible="true"
- [ ] Enable/Disable standard HTML colorpicker independently of other colorpicker parts using a boolean attribute
- [ ] Click the swatch to select / option for the "advanced" picker
- [ ] Add side by side example

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes remaining Bugs/Features for a 100% IdsColorPicker Component

**Related github/jira issue (required)**:

Closes #551

**Steps necessary to review your pull request (required)**:

See examples components below:
- http://localhost:4300/ids-color/example.html
- http://localhost:4300/ids-color-picker/example.html
- http://localhost:4300/ids-color-picker/example-sizes.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — COMMENTED** [review]
Looks pretty good so far!  I saw one usability thing with the tooltip -- appears that there's one coming from the field swatch no matter the setting:

Screen Shot 2022-05-31 at 1 13 13 PM

File: src/components/ids-color-picker/ids-color-picker.ts [hunk 1]
```diff
@@ -70,94 +89,226 @@ export default class IdsColorPicker extends Base {
...
+  get colorPopupHtml(): string {
+    return `
+      <ids-trigger-button
+        id="ids-color-picker-menu-button"
+        class="color-picker-trigger-btn"
+        ${this.disabled ? 'disabled="true"' : ''}
+        ${this.readonly ? 'readonly="true"' : ''}
+        tabbable="false"
+      >
+        <ids-text audible="true">color picker trigger</ids-text>
```
Comment (andriivarhanov) [inline src/components/ids-color-picker/ids-color-picker.ts:132]: it should be translated text from locale, I'm just not sure which one, it looks like we don't have `ColorpickerTriggerButton` key in locale messages @tmcconechy could you please advise what to use here?

**Review by andriivarhanov — COMMENTED** [review]
looks good, nothing major, some findings:
- please fix tests and prod build
- when setting input value and open popup the value should be focused

image

File: src/components/ids-color-picker/ids-color-picker.ts [hunk 2]
```diff
@@ -21,42 +23,59 @@ export default class IdsColorPicker extends Base {
...
+    this.#updateColor(this.value);
+
     this.#attachEventHandlers();
   }
 
+  /** @returns {string[]} this component's observable attributes */
   static get attributes() {
     return [
       ...super.attributes,
       attributes.ADVANCED,
```
Comment (andriivarhanov) [inline src/components/ids-color-picker/ids-color-picker.ts:70]: please list all used attributes here

File: test/ids-color/ids-color-func-test.ts [hunk 3]
```diff
@@ -26,13 +26,156 @@ describe('Ids Color Component', () => {
...
+
+    color.showTooltip();
+
+    expect(color.getAttribute('tooltip')).toEqual('Black');
+    expect(color.tooltip).toEqual('');
+    expect(color.popup.innerText).toEqual('');
+    expect(color.popup.visible).toEqual(false);
+  });
+
+  it.skip('shows black checkmark when IdsColor.class contains "light" class', () => {
```
[the remark this answers is not in the document]
Comment (tmcconechy) [reply test/ids-color/ids-color-func-test.ts:110]: I dont mind skipped tests as a TODO point for later.

File: src/components/ids-color-picker/ids-color-picker.ts (hunk 1 above)
Comment (tmcconechy) [reply src/components/ids-color-picker/ids-color-picker.ts:132]: you can put a new one in locale/cultures/en-us.js -> just put the english string in that one file for now like `TimepickerTriggerButton`

It will eventually get translated from there. However im not sure about the current text. I think it should be something like: "Click to Open Color Picker" and we change TimepickerTriggerButton as well.

File: src/components/ids-color-picker/ids-color-picker.ts [hunk 4]
```diff
@@ -70,94 +89,226 @@ export default class IdsColorPicker extends Base {
...
+  get colorPickerAdvancedHtml(): string {
+    return `
+      <label class="advanced-color-picker">
+        <input
+          class="color-input"
+          tabindex="-1"
+          type="color"
+          ${!this.advanced || this.disabled || this.readonly ? 'disabled="true"' : ''}
+        />
+        <ids-text audible="true">Pick Custom Color</ids-text>
```
[the remark this answers is not in the document]
Comment (tmcconechy) [reply src/components/ids-color-picker/ids-color-picker.ts:171]: Same see above - I think click to open color picker still applies so can use the same new translation in 2 places

File: src/components/ids-color-picker/ids-color-picker.scss [hunk 5]
```diff
@@ -24,38 +58,42 @@ ids-input::part(container) {
...
+  bottom: 0;
+  right: 0;
 
-.color-input {
-  display: block;
-  height: calc(100% + 12px);
-  margin: 0;
-  padding: 0;
-  opacity: 0;
+  .color-input {
```
Comment (danielortiz1982) [inline src/components/ids-color-picker/ids-color-picker.scss:82]: @clayinfor  This look great so far. I can not tell, can you please sure any `position: absolute` selector has a parent that is `position: relative` Thanks!

File: src/components/ids-color-picker/README.md [hunk 6]
```diff
@@ -12,7 +12,10 @@ The Color Picker by default supports colors within a pre-configured palette of I
 - `value` {string} Sets the value attribute to displayed the color of selected `value="#b94e4e"`
 - `label` {string} Sets the label attribute which will be displayed above the color picker web component `label="Color Picker"`
 - `disabled` {boolean} Sets the disabled attribute which will disabled the entire color picker web component `disabled="true"` Valid values are 'true' | 'false'
-- `readyonly` {boolean} Sets the readonly attribute. Valid values are 'true' | 'false'
+- `readonly` {boolean} Sets the readonly attribute. Valid values are 'true' | 'false'
+- `labels` {boolean} If true, the color-swatchs will display labels instead of the hex-values. Valid values are 'true' | 'false'
+- `tooltips` {boolean} If true, the color-swatchs will display tooltips on mouseover. Valid values are 'true' | 'false'
```
Comment (tmcconechy) [inline src/components/ids-color-picker/README.md:17]: Could consider the setting `suppressTooltips` i used elsewhere where its on by default. Not sure whats the best here so just putting this as an option

File: src/components/ids-color-picker/ids-color-picker.scss [hunk 7]
```diff
@@ -24,38 +58,42 @@ ids-input::part(container) {
 }
 
 .color-popup {
-  contain: content;
+  // removed `contain: content` because it prevents tooltip from appearing
+  // contain: content;
```
Comment (tmcconechy) [inline src/components/ids-color-picker/ids-color-picker.scss:62]: Can fully remove. Not really needed. But it helps with rendering performance when possible

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Some smaller issues (mostly minor but worth a quick look if possible)

1. on http://localhost:4300/ids-color/example.html if you tab through, some have a nice focus state and some are missing. Also can the focus ring have a border radius?
2. similar on the popup i see a double focus state (outline showing)
Not show here i couldnt screen shot it:
Screen Shot 2022-06-01 at 10 16 26 AM
3. can make the width bigger on the tooltip
Screen Shot 2022-06-01 at 10 19 55 AM

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@clayinfor the only thing im wondering is whats up with this page https://percy.io/00aaa841/enterprise-wc/builds/18745859/changed/1051830286?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280 ?

Do we need a quick adjustment to the responsive grid?

File: src/components/ids-color-picker/demos/example.html [hunk 8]
```diff
@@ -13,157 +13,96 @@
...
           <ids-color hex="#292929"></ids-color>
           <ids-color hex="#383838"></ids-color>
           <ids-color hex="#454545"></ids-color>
           <ids-color hex="#5C5C5C"></ids-color>
           <ids-color hex="#737373"></ids-color>
-          <ids-color hex="#999999"></ids-color>
-          <ids-color hex="#BDBDBD"></ids-color>
-          <ids-color hex="#D8D8D8"></ids-color>
-          <ids-color hex="#F0F0F0"></ids-color>
+          <ids-color hex="#999999" class="light"></ids-color>
```
[the remark this answers is not in the document]
Comment (clayinfor) [reply src/components/ids-color-picker/demos/example.html:27]: will change these class-names to `light-color` / `dark-color`... these class-names are what determine if a light-checkmark or dark-checkmark is used...

[the remark this answers is not in the document]
Comment (tmcconechy) [reply src/components/ids-color-picker/demos/example.html:27]: Sure now that its merged anything else just do a new PR. Sorry if i missed waiting for some details.
