### PR TITLE
1878 ids dropdown prevent duplicate dropdown-lists when reset datagrid

### LINKED ISSUE #1878: IdsDropdown: Prevent the "enter" key here from opening the dropdown
**Describe the bug**
We need a way to prevent the "enter" key here from firing the open event of the dropdown. This is because the enter key functions as a form submission to server side filter/position. 

Also, discovered weird behavior when setting the idsDatagrid.data with a same value(acts as data refresh), the ids-dropdown-list DOM element doubles.

**To Reproduce**
For 1st Issue: Press enter on Dropdown filter (Will open the datagrid filter and has no means of not allowing this to happen)

For 2nd Issue: 
See zip attached is a code modification of the multiple-virtual-scroll files in wc code which added a "reset data button" which recalls the setData method.
[multiple-virtual-scroll.zip](https://github.com/infor-design/enterprise-wc/files/14353398/multiple-virtual-scroll.zip)

For 1st Issue:
1. Go to http://localhost:4300/ids-data-grid/filter-trigger-fields.html
2. Focus on NotFilteredItem Dropdown filter
3. Press Enter
4. Not possible in code to stop the enter event from preventing the opening of the dropdown

**Expected behavior**
Allow in code to stop the enter key event from firing to open the dropdown filter

For 2nd Issue:
1. Open zip file attached named multiple-virtual-scroll.zip and overwrite html and ts file in WC code with the same name "multiple-virtual-scroll"
2. Open http://localhost:4300/ids-data-grid/multiple-virtual-scroll.html
3. Click the Reset Data
4. Open Developer tools and look for ids-dropdown-list DOM element with ID = "ids-data-grid-filter-inStock-2-dropdown-list"
5. See error as ids-dropdown-list has duplicate element with same ID

**Expected behavior**
When resetting the datagrid data, DOM has to be unique. Only one ids-dropdown-list should be present.

**Version**
1.0.0-beta.21

**Screenshots**
image

**Platform**
Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
OS Version: [e.g. Windows 10 or iOS 8]
Browser Name: Google chrome
Browser Version: 121.0.6167.185 (Official Build) (64-bit)

**Additional context**
Discussed in teams:
https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1708073343085?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1708073343085&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1708073343085

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fix a bug that causes duplicate dropdown-lists in the DOM when data-grid data is reset.

**Related github/jira issue (required)**:

Closes #1878 

**Steps necessary to review your pull request (required)**:

1. Check out this PRs' branch and run: `nvm use && npm install && npm run start`
2. Go to: http://localhost:4300/ids-data-grid/multiple-virtual-scroll.html
3. Preset the "reset" button a couple times.
4. Open your chrome dev console.
5. Ensure that the following command returns only one element: `$('ids-data-grid').shadowRoot.querySelectorAll('ids-dropdown-list');`

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-data-grid/ids-data-grid-filters.ts [hunk 1]
```diff
@@ -750,7 +750,7 @@ export default class IdsDataGridFilters {
       let triggerField = node?.querySelector('ids-trigger-field');
       const datePickerPopup = node?.querySelector('ids-date-picker-popup');
       const timePickerPopup = node?.querySelector('ids-time-picker-popup');
-      let menuAttachment = '.ids-data-grid-wrapper';
+      let menuAttachment = '.ids-data-grid';
```
Comment (clayinfor) [inline src/components/ids-data-grid/ids-data-grid-filters.ts:753]: This line is what was causing the duplicate the dropdown popup menu in the data-grid's shadowRoot... If you revert this line, you can follow the testing instructions in the PR and confirm that duplicate popups were appearing in the DOM after clicking the "reset" button.

**Comment by tmcconechy** [comment]
@clayinfor in the steps?

1. whats the reset button? Browser reload?
2. When i ran that command i got zero (empty NodeList)

Fix looks fine but wasnt sure how to test. Think it needs a unit test too?

**Comment by clayinfor** [comment]
Hey @tmcconechy , the "reset data" button simply updates the data-grid's data.

The bug that existed caused multiple `ids-dropdown-list` elements (under the "In Stock" column header) to be created in the shadowRoot whenever the data-grid's data was updated (or reset).  This PR fixes it so that this bug doesn't occur.

**Review by tmcconechy — APPROVED** [review]

**Review by jdilag90 — APPROVED** [review]
