### PR TITLE
2207 - IdsDatePicker input value sync

### LINKED ISSUE #2207: IdsDatePicker: Changing textbox manually does not change the value passed by the component
When working with the ids-date-picker in react, updating the date using the calendar popup works as intended.  If I were to use the textbox and not activate the calendar again, the date that passes into validation and submission is not the one I typed in, but instead the one that was within the calendar selection.

To reproduce, simply go to a date picker and click to open the calendar
Select a date to close the calendar popup
Now enter the textbox and type in a different date
Submit the date and see what value is returned

To get around the issue, I have coded my date check to get both values and then compare if they are the same or different using the following initializing code using a date picker with an id of "DateStart":

```
    let dateInputPicker = (idsForm?.formComponents.find(item => item.id == "DateStart") as IdsDatePicker);    
    let dateInputPickerShadowroot = dateInputPicker?.shadowRoot?.querySelector("#DateStart") as IdsTriggerField;  
    let inputDateStart = dateInputPicker?.value  
    let inputDateStartShadowroot = dateInputPickerShadowroot?.value;
```

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixes issue where manual date inputs didn't sync with date picker value and picker popup

**Related github/jira issue (required)**:
Closes #2207 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Go to http://localhost:4300/ids-date-picker/example.html
3. Enter a date manually 
4. Check that `$('ids-date-picker').value` matches that date
5. Open popup and check that your input date is displayed and selected

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-date-picker/ids-date-picker.ts [hunk 1]
```diff
@@ -370,6 +370,14 @@ class IdsDatePicker extends Base {
       this.#togglePopup(false);
     });
 
+    // Input value change
+    this.offEvent('change.date-picker-input');
+    this.onEvent('change', this.triggerField, (e) => {
```
Comment (andrivarhanov) [inline src/components/ids-date-picker/ids-date-picker.ts:375]: could you please use same event name here `onEvent('change.date-picker-input', ...`

**Review by tmcconechy — APPROVED** [review]
