### PR TITLE
904, 1230 - Fix to remove hash links for navigation with scroll view

### LINKED ISSUE #904: IdsScrollView: Remove hash links for navigation
**Describe the bug**
Find an alternate solution to using hash links in the ids-scroll-view component to avoid issues within SPA frameworks routing systems

**To Reproduce**

1. Pull angular-ids-wc example branch https://github.com/infor-design/enterprise-wc-examples/tree/316-angular-examples
2. `npm i && start`
3. go to http://localhost:4200/ids-scroll-view/example

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed to remove hash links for navigation with scroll view
- Changed the logic to move the slides
- Add api methods (play, stop, toggle, first, last, previous, next, slideTo)
- Add events (some veto able)
- Add tests/covrage

**Related github/jira issue (required)**:
Closes #904
Closes #1230
NG Examples: https://github.com/infor-design/enterprise-wc-examples/pull/32

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300/ids-scroll-view/example.html
- http://localhost:4300/ids-scroll-view/sandbox.html
- See url when move slides, does not use hash links
- See the api calls should work
- Click on the circles, should not focus state (only should focus with keyboard)
- Should work fine with other platforms(angular etc..)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-scroll-view/ids-scroll-view.ts [hunk 1]
```diff
@@ -64,105 +75,488 @@ export default class IdsScrollView extends Base {
...
+      const current = timestamp();
+      const diff = current - start;
+      if (diff >= this.delay) {
+        start = timestamp();
+        callback();
+        if (isOnce) cancelAnimationFrame(this.#slideRafId);
       }
-      this.#activateLink(event.target, true);
-      this.isClick = true;
+    };
```
Comment (jdilag90) [inline src/components/ids-scroll-view/ids-scroll-view.ts:285]: Can we use a setTimeout to handle delay instead of a raf? If you insert a `console.log` inside `repeatOften()` you can see the function gets run ~1k times on a 60hz display.

Comment (jdilag90) [reply src/components/ids-scroll-view/ids-scroll-view.ts:285]: Everything else looks good, one other thing. `currentSlideNumber()` sometimes returns a decimal since `scrollLeft` is used in the calculation

Comment (deep7102) [reply src/components/ids-scroll-view/ids-scroll-view.ts:285]: Thanks! @jdilag90 
 - Updated now, `currentSlideNumber()` to be return whole number or undefined
 - About handle delay I had in mind RAF is more better in all cases epically in performance, I had read few articles in past like as: https://css-tricks.com/using-requestanimationframe/#aa-why-better or https://www.paulirish.com/2011/requestanimationframe-for-smart-animating. But after your comment I think about it more... and bit confuse now, because you have point too. It run with every frame also RAF come with some good stuff which `setTimeout()` or `setInterval()` not supported (like stops automatically when inactive, more battery-friendly etc.)
 - I can take some help here please guide, should we keep as RAF? or I can replace with `setInterval()`, because both ceases have some give or take.

Comment (tmcconechy) [reply src/components/ids-scroll-view/ids-scroll-view.ts:285]: Can we avoid both a Raf and setTimeout? Thats ideal. So far we avoided setTimeout entirely and it would be the very first one.

Comment (deep7102) [reply src/components/ids-scroll-view/ids-scroll-view.ts]: @tmcconechy @jdilag90 
Updated now, please review

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@deep7102 i think the `loop` setting was not fully removed in all places

Also in terms of functionality i see one thing
1. http://localhost:4300/ids-scroll-view/example.html
2. swipe left and it updates the pager
3. but keep swiping to the end one and the pager is not updated... ui swipe so last one is in view.

File: src/components/ids-scroll-view/README.md [hunk 2]
```diff
@@ -14,6 +14,37 @@ The scroll view component allows swipe and scroll in between a number of slides/
 - **Circle Pager**: The older 4.x name for his component
 - **Carousel**: Another name for this sort of component with slides and buttons
 
+## Settings and Attributes
+
+- `loop` {boolean} sets the loop, true will loop back after next/previous reached to end
```
[the remark this answers is not in the document]
Comment (deep7102) [reply src/components/ids-scroll-view/README.md:19]: - When swipe the pager is updating soon it stops swiping, otherwise it flickering because too many call to set selected state. It move depends on how much force was applied while swipe. 
- `loop` setting we need it use with next/previous so if it set to true it can keep going around

File: src/components/ids-scroll-view/demos/example.html [hunk 3]
```diff
@@ -14,7 +14,7 @@
       <ids-layout-grid-cell col-span="1">
         <ids-scroll-view>
           <img class="camera-1" slot="scroll-view-item" alt="Slide 1, Sony Camera, Front"/>
-          <img class="camera-2" slot="scroll-view-item" alt="Slide 3, Sony Camera, Back Display"/>
```
[the remark this answers is not in the document]
Comment (deep7102) [reply src/components/ids-scroll-view/demos/example.html:17]: Nothing wrong, looks like was just typo in alt text it should be 2nd slide so it updated

File: src/components/ids-scroll-view/ids-scroll-view.ts [hunk 4]
```diff
@@ -64,105 +70,315 @@ export default class IdsScrollView extends Base {
...
+   * @param {boolean} value The value
+   */
+  set loop(value: boolean) {
+    const val = stringToBool(value);
+    if (val === this.loop) return;
+    if (val) this.setAttribute(attributes.LOOP, '');
+    else this.removeAttribute(attributes.LOOP);
+  }
+
+  get loop(): boolean {
```
[the remark this answers is not in the document]
Comment (deep7102) [reply src/components/ids-scroll-view/ids-scroll-view.ts:135]: No need to remove this setting

File: src/components/ids-scroll-view/README.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (jdilag90) [reply src/components/ids-scroll-view/README.md:19]: I think what Tim means is that the pager loses sync with the active slide. If you swipe left to the last camera image, the last circle in `ids-scroll-view-controls` isn't shown as selected

**Review by tmcconechy — APPROVED** [review]
Not seeing it now tho. @jdilag90 did you see it. Looked ok on device simulator but not with magic mouse. But will approve since i cant see it anymore

**Review by jdilag90 — APPROVED** [review]
