### PR TITLE
501 - Add missing focus styling and fix mobile view double toggling 

### LINKED ISSUE #501: IdsAccordion: Focus Styling is incorrect in some themes
**Describe the bug**
The focus styling is ok in light mode but not in dark or contrast mode. Classic mode may be deprecated but can be just added it for now.

**To Reproduce**
1. Go to  http://localhost:4300/ids-accordion
2. Click on '....' and switch to dark (also contrast)
3. Tab into the accordion
4. See that the focus state is not complete

**Expected behavior**
Should look like https://main-enterprise.demo.design.infor.com/components/accordion/example-index.html?theme=new&mode=dark&colors=0066D4

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
- :focus styling was missing for classic/new dark/high contrast themes.
- Found issue with expanding/toggling panel twice when in mobile view. 
- Refactored ids-accordion-panel -> select() to increase code coverage 

**Related github/jira issue (required)**:
Close #501 

**Steps necessary to review your pull request (required)**:
1. Checkout branch `501-accordion-focus`
2. `npm run start`
3. Go to http://localhost:4300/ids-accordion
4. Click or tab navigate accordion panels and compare styles to 4x https://main-enterprise.demo.design.infor.com/components/accordion/example-index.html?theme=classic&mode=dark&colors=0066D4
5. Also, switch dev tools to mobile view and expand/collapse panels to ensure double toggling is fixed on mobile

IDS Accordion Component

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

File: src/components/ids-accordion/ids-accordion-panel.js [hunk 1]
```diff
@@ -348,11 +348,10 @@ export default class IdsAccordionPanel extends Base {
    * @returns {void}
    */
   select(panel) {
-    if (panel === undefined) {
-      return;
+    if (panel && panel.tagName === 'IDS-ACCORDION-PANEL') {
```
Comment (tmcconechy) [inline src/components/ids-accordion/ids-accordion-panel.js:351]:
```suggestion
    if (panel?.tagName === 'IDS-ACCORDION-PANEL') {
```

Can also do this i think?

File: src/components/ids-accordion/ids-accordion-header.scss [hunk 2]
```diff
@@ -4,6 +4,10 @@
 // Styles specific to the in-page Accordion
 
 @mixin accordion-header-standard-colors() {
+  // classic color variables
+  --ids-color-palette-classic-azure-50: #54a1d3;
```
Comment (tmcconechy) [inline src/components/ids-accordion/ids-accordion-header.scss:8]: I didnt add these on purpose so classic isnt 100% 1-1 it uses the same new color pallette.
So instead of adding all these you can just subsitute

--ids-color-palette-azure-50
--ids-color-palette-azure-60


And use whats there...

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good! Just a few small suggestions...

**Review by tmcconechy — APPROVED** [review]
Great First PR thanks @jdilag90  👍🏻

**Review by danielortiz1982 — APPROVED** [review]
@jdilag This looks great! Good job.

**Review by EdwardCoyle — APPROVED** [review]
Looks great @jdilag90!
