### PR TITLE
1179 - Add fixes for closing menu and cleanup

### LINKED ISSUE #1179: IdsDatagrid: Opening Ids contextmenu does not close Soho Contextmenu and vice versa
**Describe the bug**
I am using Soho and Ids together in a project. When I right click on a soho control/component to open a contextmenu and right click on IdsDatagrid to open a contextmenu, the soho contextmenu does not close and vice versa.

**To Reproduce**

1. Open enterprise-ng-quickstart
2. Add a soho control with a context menu on the app.component.html
3. Add a ids component with a context menu on the app.component.html
4. Add ids js file dependencies ids-input and ids-popupmenu on angular.json

**Expected behavior**
The previously opened context menu (soho) should be closed when opening a new one (ids).

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Add Soho context menu on app.component.ts
image
Add Ids context menu on app.component.ts
image
Add ids contextmenu to angular.json
image

**Platform**
 - Infor Application/Team Name: M3 H5A
 - Device:
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: Version 111.0.5563.64 (Official Build) (64-bit)
 
**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Takes the code in side-by-side that was implemented to hide menus when a menu in the older framework is opened/closes and implements it in the component as a more permanent solution.

Uses mutation observer and setting classes. Also found a mutation observer that may not be cleaned up and fixed it and some JSDoc warnings.

Note: Includes https://github.com/infor-design/enterprise-wc/pull/1251 as it caused testing issues otherwise.

**Related github/jira issue (required)**:
Fixes #1179 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-popup-menu/side-by-side.html
- right click between each component (old and new) and alternate seeing that one closes the other and vise versa

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — DISMISSED** [review]
looks good

**Comment by andriivarhanov** [comment]
@tmcconechy it looks like initial fix for the context menu doesn't work for some other menus (tests are failing for that reason), I've made another change adding hide only for context menu https://github.com/infor-design/enterprise-wc/pull/1251/files , tests should pass now

**Review by andriivarhanov — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]

File: src/components/ids-popup-menu/ids-popup-menu.ts [hunk 1]
```diff
@@ -155,12 +161,35 @@ export default class IdsPopupMenu extends Base {
...
 
+  /** Hide any older (enterprise) menus */
+  hideOtherMenus() {
+    const openMenu = (document.querySelector('.popupmenu.is-open') as HTMLElement);
+    openMenu?.classList.remove('is-open');
+    const openMenuElem = (document.querySelector('[data-popupmenu].is-open') as HTMLElement);
+    openMenuElem?.classList.remove('is-open');
+
+    // Use the is-open class to close it
+    this.#mo = new MutationObserver((mutations) => {
```
Comment (EdwardCoyle) [inline src/components/ids-popup-menu/ids-popup-menu.ts:179]: We might not want to rebuild this on every 'show' event.  These fire often, so I'd say try and set this up once in `connectedCallback`.  The above code for closing the menus can run on each `show`

File: src/components/ids-popup-menu/ids-popup-menu.ts [hunk 2]
```diff
@@ -155,12 +161,35 @@ export default class IdsPopupMenu extends Base {
...
     // Set up all the events specifically-related to the "trigger" type
     this.refreshTriggerEvents();
   }
 
+  /** Hide any older (enterprise) menus */
+  hideOtherMenus() {
+    const openMenu = (document.querySelector('.popupmenu.is-open') as HTMLElement);
+    openMenu?.classList.remove('is-open');
+    const openMenuElem = (document.querySelector('[data-popupmenu].is-open') as HTMLElement);
+    openMenuElem?.classList.remove('is-open');
```
Comment (EdwardCoyle) [inline src/components/ids-popup-menu/ids-popup-menu.ts:176]: I think it's better to fire the [popupmenu's `close()` API](https://github.com/infor-design/enterprise/blob/main/src/components/popupmenu/popupmenu.js#L2384-L2390):
```suggestion
    openMenuElem?.data('popupmenu')?.close(true, true);
```

I think this is necessary because there are events bound during `open()/close()`, among other component interactions that wouldn't be accounted for simply by using the class to hide.

**Review by EdwardCoyle — CHANGES_REQUESTED** [review]
If we add detection directly into the Popup Menu I think we might need a safer approach.  Please see below

File: src/components/ids-popup-menu/ids-popup-menu.ts (hunk 2 above)
Comment (tmcconechy) [reply src/components/ids-popup-menu/ids-popup-menu.ts:176]: @EdwardCoyle while this would be better it would require using the jQuery API and introduce a dependency. Since this is about cancelling it only I think it would be fine so i did it this way.

File: src/components/ids-popup-menu/ids-popup-menu.ts (hunk 1 above)
Comment (tmcconechy) [reply src/components/ids-popup-menu/ids-popup-menu.ts:179]: What if we do it only if elements are found in the page on the show? Think that would fly? I was thinking that maybe we dont add it unless we need it sort of thing.

**Review by EdwardCoyle — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
LGTM 🍌
