### PR TITLE
2191 - IdsHierarchy popup position

### LINKED ISSUE #2191: IdsHierarchy: popup behind the field
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-hierarchy/example.html
2. Click on '....' to open pop up
3. verify each '...'

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

this could be a problem in smaller viewports
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
All

**Additional context**

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed the issue where a popup appeared behind the field by adjusting hierarchy item z-index

**Related github/jira issue (required)**:
Closes #2191 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-hierarchy/example.html
- click on '....' to open the popup
- see the hierarchy items don't overlap the popup

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

File: src/components/ids-hierarchy/ids-hierarchy-item.ts [hunk 1]
```diff
@@ -310,7 +310,7 @@ export default class IdsHierarchyItem extends Base {
 
     if (this.dropdownMenu) {
       this.onEvent('click', this.dropdownMenu, () => {
-        this.adjustZIndex(this.parentNode, 202);
+        this.adjustZIndex(this.parentNode, 102);
```
Comment (tmcconechy) [inline src/components/ids-hierarchy/ids-hierarchy-item.ts:313]: @andrivarhanov just for following a system i have in place if this is an ids-popup i think this should be

```
1015
```

FYI

```
20 - Contextual Toolbar
500 - Side Menu, Status Bar
600 - App Menu, Module Nav
1000 - Overlay
1010 - Busy Indicator
1015 - Popdown
1020 - Dialogs (Modals)
3000 - Popovers 
4000 - Lookup
4500 - Drop Down
6000 - Tooltips
7000 - Draggables
8000 - Slide in Message Dialog/Toast
9000 - Sticky Nav / Context Menus
10000 - Full Page Sticky Nav, Search Results
10020 - Skip link
```

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.

**Windows Chrome**
image

**Mobile**
image

**Safari**
image
