### PR TITLE
1031 - Improve accessibility with date picker

### LINKED ISSUE #1031: IdsDate Picker: A11Y: Calendar is not properly accessible through screen reader.
**Describe the bug**
Calendar is not properly accessible through screen reader.

WCAG Guideline: 2.1.1 Keyboard

**To Reproduce**

1. Launch the URL: https://main.wc.design.infor.com/ids-date-picker/example.html
2. Navigate to date widget using arrow keys and verify
3. Calendar is not properly accessible through screen reader. While navigating inside calendar screen reader remain silent and does not read the controls.

**Expected behavior**
Calendar should be properly accessible through screen reader.

User Impact: If calendar will not be accessible then screen reader user will not be able to access its functionality.

**Screenshots**
https://www.screencast.com/t/lXnaxipSq

**Platform**

 - Windows 10
 - Browser Name: Chrome

**Additional context**
Add any other context about the problem here. None

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
Improved date picker accessibility (A11Y) calendar was not properly accessible through screen reader

**Related github/jira issue (required)**:
Closes #1031

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to: http://localhost:4300/ids-date-picker/example.html
- Use arrow keys to verify date picker
- Calendar should properly accessible through screen reader, while navigating inside calendar.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/ids-date-picker/ids-date-picker-popup.ts [hunk 1]
```diff
@@ -195,7 +195,7 @@ class IdsDatePickerPopup extends Base implements IdsRangeSettingsInterface {
       <ids-toolbar-section favor>
         <ids-toggle-button id="month-year-view-trigger" icon-off="dropdown" icon-on="dropdown" icon="dropdown" icon-align="end" no-padding class="dropdown-btn">
           <ids-text audible="true" translate-text="true">DatePickerTriggerButton</ids-text>
-          <ids-text class="dropdown-btn-text" font-size="20">${this.formatMonthText()}</ids-text>
+          <ids-text class="dropdown-btn-text" font-size="20" aria-live="polite">${this.formatMonthText()}</ids-text>
```
Comment (tmcconechy) [inline src/components/ids-date-picker/ids-date-picker-popup.ts:198]: The only thing im wondering about is the use of aria-live here. I have a feel but not sure that this would be incorrect use of it. Is there anything like an aria-label or aria-description or aria-described-by that will work.

Comment (deep7102) [reply src/components/ids-date-picker/ids-date-picker-popup.ts:198]: soon the month/year change need to announce, but since our focus going to be on date cell aria-live will handle to announce month/year update

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
